language: python

sudo: required

services:
  - docker

python:
  - 2.7

before_install:
  - export DJANGO_SETTINGS_MODULE=happny.settings.travis

install:
  - pip install -r requirements.txt

env:
  - DJANGO=1.9.6

script:
  - python manage.py test

